#!/bin/bash
# Быстрая шпаргалка по Git для zadachnik

echo "═══════════════════════════════════════════════════════════"
echo "  Git Шпаргалка для Self's Product Board"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🚀 БЫСТРАЯ СИНХРОНИЗАЦИЯ:"
echo "   ./s                          # Сверхбыстро!"
echo "   ./sync_github.sh             # Обычная"
echo ""
echo "🤖 АВТОМАТИЧЕСКАЯ СИНХРОНИЗАЦИЯ:"
echo "   python auto_sync.py          # Запустить в фоне"
echo "   (Ctrl+C для остановки)"
echo ""
echo "📤 ОТПРАВИТЬ С СООБЩЕНИЕМ:"
echo "   python sync_github.py \"Текст сообщения\""
echo ""
echo "📥 ПОЛУЧИТЬ ИЗМЕНЕНИЯ С GITHUB:"
echo "   git pull origin main"
echo ""
echo "📊 ПРОВЕРИТЬ СТАТУС:"
echo "   git status"
echo ""
echo "📜 ИСТОРИЯ КОММИТОВ:"
echo "   git log --oneline -10"
echo ""
echo "🔄 ПЕРВАЯ НАСТРОЙКА (один раз):"
echo "   1. Создайте Personal Access Token:"
echo "      https://github.com/settings/tokens"
echo "   2. Выполните: git push -u origin main"
echo "   3. Введите username: suicidelexus"
echo "   4. Введите password: ваш токен"
echo ""
echo "💻 НА ДРУГОМ КОМПЬЮТЕРЕ (первый раз):"
echo "   git clone https://github.com/suicidelexus/zadachnik.git"
echo "   cd zadachnik"
echo "   pip install -r requirements.txt"
echo ""
echo "🆘 ПОМОЩЬ:"
echo "   Автосинхронизация: cat AUTO_SYNC_GUIDE.md"
echo "   Настройка GitHub: cat GITHUB_SETUP_GUIDE.md"
echo ""
echo "═══════════════════════════════════════════════════════════"

